# Generated by Django 3.2.8 on 2024-02-27 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0004_auto_20240227_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
