# Generated by Django 3.2.8 on 2024-02-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_comentario_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='calificacion',
        ),
    ]
